### ISSUE TITLE
Please promote version 1.9.0 to stable

### ISSUE THREAD

**Issue by lengau** [iosifache/osv-scanner-snap#1]
Hi! Could you please make a version of the snap that contains the `v1.9.0` tag of `osv-scanner` and release it to stable?

You can do that by adding the key/value pair `source-tag: v1.9.0` to the `osv-scanner` part in snapcraft.yaml for the build.

As a side note, the snapcrafters group have some nice CI if you just want to sync stable versions and release those to the stable or candidate branches. [This workflow](https://github.com/snapcrafters/ruff/blob/candidate/.github/workflows/sync-version-with-upstream.yaml) syncs based on a GitHub release. (If you want to also do nightlies on the edge channel, the easiest way to do that is with two separate branches.)

**Comment by iosifache** [comment]
Hi Alex,

I wanted to ACK the issue. I will do the upgrade later today!

**Comment by iosifache** [comment]
@lengau, I just released a new version 🙌🏻.

I will set up the workflow that you mentioned, thanks for the recommendation!

**Comment by lengau** [comment]
Thanks @iosifache! You fixed our CI! (The version that was on the stable channel was crashing, believe it or not) 

If you'd like some help with the workflows I'd be happy to assist.
